version: '3.8'
services:
  mongodb:
    image: mongo:5.0.0-focal
    container_name: mondodb
    ports:
      - '27017:27017'
  redis:
    image: redis:alpine
    command:
      - redis-server
    ports:
      - '6379:6379'
    container_name: redis
